spring:
  application:
    name: "KarandaServer"
  profiles:
    active: "production"
  data:
    redis:
      repositories:
        enabled: false
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1

# Open API Swagger
springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  servlet:
    # Set utf-8
    encoding:
      charset: utf-8
      force: true

# Custom Properties (Immutable data)
karanda:
  adventurer-profile-url-base:
    kr: "https://www.kr.playblackdesert.com/ko-KR/Adventure/Profile"
    na: "https://www.naeu.playblackdesert.com/en-US/Adventure/Profile"
    eu: "https://www.naeu.playblackdesert.com/en-US/Adventure/Profile"
    jp: "https://www.jp.playblackdesert.com/ja-JP/Adventure/Profile"

---
# Production profile
spring:
  config:
    activate:
      on-profile: "production"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PW}
    hikari:
      max-lifetime: 177000  # 177초
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 20
server:
  port: 8080
management:
  server:
    port: 1234
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"


---
# Develop profile
spring:
  config:
    activate:
      on-profile: "develop"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./localDB/dev
    username: user
    password: 1234
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 20
server:
  port: 8000
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: trace