spring:
  application:
    name: "KarandaServer"
  profiles:
    active: "production"

# Open API Swagger
springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  servlet:
    # Set utf-8
    encoding:
      charset: utf-8
      force: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: "production"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DB_HOST}
    username: {DB_USER}
    password: {DB_PW}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
server:
  port: 8080

---
# Develop profile
spring:
  config:
    activate:
      on-profile: "develop"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./localDB/dev
    username: user
    password: 1234
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 20
server:
  port: 8000
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: trace